---
name: "Nix-related checks"
"on":
  push:
    branches:
      - main

jobs:
  nix-flake-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Run nix flake check"
        run: nix flake check

  build-package:
    strategy:
      matrix:
        snowcliVer: ["2x", "3x"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Build Snowcli {{ matrix.snowcliVer }}"
        run: nix build .#snowcli-${{ matrix.snowcliVer }}
      - name: "Run sample Snowcli command"
        run: nix run .#snowcli-${{ matrix.snowcliVer }} -- --version
